name: harena
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter 

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.2
  chewie: ^1.3.5
  intl: ^0.17.0
  get: ^4.6.5
  http: ^0.13.5
  shared_preferences: ^2.0.18
  dio: ^5.0.1
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
        # Add this line
  
  flutter_lints: ^2.0.0


flutter:
  
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/harena3.png
    - assets/harena4.png
    - assets/
  
